### ISSUE TITLE
_util.promisify is not a function

### ISSUE THREAD

**Issue by delichty** [AtomLinter/linter-jsonlint#112]
[Enter steps to reproduce:]

1. Start Atom

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 14.04.6
**Thrown From**: [linter-jsonlint](https://github.com/AtomLinter/linter-jsonlint) package 1.4.0

### Stack Trace

Failed to activate the linter-jsonlint package

```
At (0 , _util.promisify) is not a function

TypeError: (0 , _util.promisify) is not a function
    at /packages/linter-jsonlint/node_modules/sb-fs/lib/index.js:17:46
    at Array.forEach (native)
    at /packages/linter-jsonlint/node_modules/sb-fs/lib/index.js:13:26)
    at /packages/linter-jsonlint/node_modules/sb-fs/lib/index.js:51:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-jsonlint/node_modules/atom-package-deps/lib/helpers.js:10:36)
    at /packages/linter-jsonlint/node_modules/atom-package-deps/lib/helpers.js:196:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-jsonlint/node_modules/atom-package-deps/lib/index.js:10:39)
    at /packages/linter-jsonlint/node_modules/atom-package-deps/lib/index.js:55:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/linter-jsonlint/lib/index.js:10:3)
```

### Commands

```
     -3:27.3.0 intentions:highlight (input.hidden-input)
     -3:26.9.0 settings-view:open (input.hidden-input)
     -2:56.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-cisco-syntax 0.1.0 
atom-jq 0.7.0 
block-comment 0.4.3 
busy-signal 2.0.1 
ex-mode 0.18.0 
file-type-icons 1.3.4 
git-plus 8.1.0 
git-projects 1.17.0 
imdone-atom 2.4.31 
intentions 1.1.5 
jsonlint 1.1.4 
language-apache 1.8.0 
language-bats 0.1.0 
language-cisco 1.6.4 
language-crontab 1.0.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-fortigate 0.3.0 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-ini 1.20.0 
language-juniper-junos 1.0.0 
language-powershell 5.0.0 
language-routeros-script 0.2.0 
language-scala 1.1.10 
language-terraform 0.8.1 
language-transact-sql 0.0.11 
language-vbscript 0.9.0 
linter 2.3.0 
linter-jsonlint 1.4.0 
linter-terraform-syntax 1.2.6 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
new-tab 0.5.3 
pinned-tabs 2.1.1 
pretty-json 2.1.2 
scroll-sync 0.2.4 
split-diff 1.6.0 
ssh-config 0.14.0 
symbols-tree-view 0.14.0 
teletype 0.13.3 
terminal-tab 0.5.7 
terraform-fmt 0.3.0 
tree-view-git-status 1.5.2 
vim-mode 0.66.0 
xml-formatter 0.13.0 
```

**Comment by delichty** [comment]
Thought I had Atom up to date, but was using an old Ubuntu repo. I have now updated it to 1.36.1 and the error has cleared up.
