### ISSUE TITLE
Failed to activate the linter-jsonlint package

### ISSUE THREAD

**Issue by mitorez** [AtomLinter/linter-jsonlint#34]
[Enter steps to reproduce below:]

1. Install 'linter-jsonlint' package.
2. Receive error.

**Atom Version**: 1.4.3
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [linter-jsonlint](https://github.com/AtomLinter/linter-jsonlint) package, v1.1.5

### Stack Trace

Failed to activate the linter-jsonlint package

```
At Cannot find module 'atom-package-path'

Error: Cannot find module 'atom-package-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.install (C:\Users\TW038717\.atom\packages\linter-jscs\node_modules\atom-package-deps\lib\main.js:27:12)
    at Function.activate (C:/Users/TW038717/.atom/packages/linter-jsonlint/lib/index.js:11:34)
    at Package.module.exports.Package.activateNow (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:183:20)
    at C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:92:15)
    at C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package-manager.js:524:21)
    at C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\TW038717\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -7:57.6.0 settings-view:open (atom-pane.pane.active)
     -7:45.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:57.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
  3x -4:55.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:08.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
file-icons, v1.6.14
language-batchfile, v0.4.0
language-groovy, v0.5.0
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-jscs, v3.4.4
linter-jshint, v1.3.0
linter-jsonlint, v1.1.5

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Sounds like an npm caching problem
Here's the solution
```
cd ~/.atom/packages/linter-jsonlint
npm install atom-package-path@latest
```

**Comment by mitorez** [comment]
Thanks @steelbrain - that fixed it. I actually only opened this issue b/c I got the same error on 4 linter packages I installed in a row and 'jsonlint' was the only one Atom said didn't have an issue open for it - didn't know if there was an underlying issue that needed to be addressed. Thanks again for the quick reply.

**Comment by Arcanemagus** [comment]
Looks like you happened to install things right in the middle of a problem with the deployment of `atom-package-path`, sorry about that!

**Comment by td-gonzales** [comment]
@Arcanemagus 
I just got this error so I think it's still a problem.

**Comment by Arcanemagus** [comment]
@td-gonzales If you got this then you simply ran into Atom's persistent (but random) bug where it fails to install all dependencies. If re-installing the plugin doesn't resolve the issue for you can you open a new issue to debug this further?

**Comment by td-gonzales** [comment]
@Arcanemagus I just went in through the command line as mentioned above. Is this an atom issue or an NPM issue? I have seen a few dependency failures in the last couple of days. It seems like a real mess.

**Comment by Arcanemagus** [comment]
Atom issue, and it is :confused:

Most of the time it just fails to install a dependency, occasionally it will just not download all the files though. I'm guessing it's due to the _ancient_ version of `npm` that `apm` wraps, but I have no idea for sure.
