### ISSUE TITLE
Failed to load the linter-jsonlint package

### ISSUE THREAD

**Issue by lifeless365** [AtomLinter/linter-jsonlint#84]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [linter-jsonlint](https://github.com/AtomLinter/linter-jsonlint) package 1.3.0

### Stack Trace

Failed to load the linter-jsonlint package

```
At Cannot find module 'jsonlint'

Error: Cannot find module 'jsonlint'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-jsonlint-1.3.0/lib/index.js:3:29)
    at /packages/linter-jsonlint-1.3.0/lib/index.js:40:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.2/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:937:35)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.23.2/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:529:23)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/atom-environment.js:832:34
```

### Commands

```
```

### Non-Core Packages

```
ide-json 0.1.0 
linter-jsonlint 1.3.0 
pretty-json 1.6.4 
```

**Comment by Arcanemagus** [comment]
Please try re-installing the package, it seems that the `jsonlint` dependency wasn't installed by `apm`.
